# Deep Learning using Tensorflow

## Churn_Modelling dataset

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# read the dataset
data = pd.read_csv('Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [2]:
# X = columns from 3 to second last
# Y = last column
X = data.iloc[:,3:-1].values
print(X)
Y = data.iloc[:,-1:].values
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [0]]


### Encoding categorical variable

In [3]:
#Lable encoding "Gender" column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [4]:
#OneHot encoding "Geography" column

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset

In [5]:
#Splitting X and Y datasets into 80% training and 20% testing sets

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)


### Feature scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
print("X_train\n",X_train)
X_test = sc.transform(X_test)
print("X_test\n",X_test)

X_train
 [[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
X_test
 [[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


### Building ANN

In [7]:
#Initialising ANN
ann = tf.keras.models.Sequential()

#Adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training the ANN

In [8]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#Training ANN on training set
ann.fit(X_train, Y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5054 - accuracy: 0.7934
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4548 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4339 - accuracy: 0.8034
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4214 - accuracy: 0.8079
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4101 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3988 - accuracy: 0.8199
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3876 - accuracy: 0.8275
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3785 - accuracy: 0.8321
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3716 - accuracy: 0.8410
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3674 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3345 - accuracy: 0.8640
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3345 - accuracy: 0.8651
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3344 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3341 - accuracy: 0.8629
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3343 - accuracy: 0.8616
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3333 - accuracy: 0.8634
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8649
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3335 - accuracy: 0.8629
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 

### Predicting the test set results

In [17]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [11]:
Y_pred.shape

(2000, 1)

### Making confusion matrix and calculating accuracy

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
acc = accuracy_score(Y_test, Y_pred)
print('Accuracy=', acc)

[[1515   80]
 [ 199  206]]
Accuracy= 0.8605
